package com.verify_x.enums;

public enum TechnicalSkill {
    C,
    CPP,
    JAVA,
    PYTHON,
    CSHARP,
    GO,
    RUST,
    PHP,
    RUBY,
    KOTLIN,
    SWIFT,
    DART,
    SCALA,
    HTML,
    CSS,
    JAVASCRIPT,
    TYPESCRIPT,

    REACT_JS,
    NEXT_JS,
    ANGULAR,
    VUE_JS,
    NUXT_JS,
    SVELTE,
    BOOTSTRAP,
    TAILWIND_CSS,
    MATERIAL_UI,
    SPRING,
    SPRING_BOOT,
    SPRING_MVC,
    SPRING_SECURITY,
    SPRING_CLOUD,
    HIBERNATE,
    JPA,
    NODE_JS,
    EXPRESS_JS,
    NEST_JS,
    DJANGO,
    FLASK,
    FAST_API,
    DOT_NET,
    ASP_NET,
    ASP_NET_CORE,
    ASP_NET_MVC,
    LARAVEL,
    RUBY_ON_RAILS,
    GIN,
    ECHO,
    SQL,
    MYSQL,
    POSTGRESQL,
    SQL_SERVER,
    ORACLE,
    SQLITE,
    MARIADB,
    MONGODB,
    FIREBASE,
    FIRESTORE,
    DYNAMODB,
    CASSANDRA,
    NEO4J,
    REDIS,
    MEMCACHED,
    AWS,
    AWS_EC2,
    AWS_S3,
    AWS_RDS,
    AWS_LAMBDA,
    AZURE,
    AZURE_APP_SERVICE,
    AZURE_FUNCTIONS,
    AZURE_SQL_DATABASE,
    GOOGLE_CLOUD,
    GOOGLE_CLOUD_RUN,
    GIT,
    GITHUB,
    GITLAB,
    BITBUCKET,
    DOCKER,
    KUBERNETES,
    HELM,

    JENKINS,
    GITHUB_ACTIONS,
    GITLAB_CI_CD,
    TERRAFORM,
    ANSIBLE,
    NGINX,
    APACHE,
    REST_API,
    GRAPHQL,
    SOAP,
    WEBSOCKET,
    APACHE_KAFKA,
    RABBITMQ,
    APACHE_ACTIVEMQ,
    MANUAL_TESTING,
    AUTOMATION_TESTING,

    JUNIT,
    TESTNG,
    MOCKITO,

    SELENIUM,
    CYPRESS,
    PLAYWRIGHT,

    POSTMAN,
    REST_ASSURED,
    MACHINE_LEARNING,
    DEEP_LEARNING,
    ARTIFICIAL_INTELLIGENCE,
    NATURAL_LANGUAGE_PROCESSING,
    COMPUTER_VISION,
    TENSORFLOW,
    PYTORCH,
    SCIKIT_LEARN,
    NUMPY,
    PANDAS,
    MATPLOTLIB,
    JUPYTER,
    GENERATIVE_AI,
    LARGE_LANGUAGE_MODELS,
    PROMPT_ENGINEERING,
    RAG,
    AI_AGENTS,
    LANGCHAIN,
    LLAMA_INDEX,
    PINECONE,
    MILVUS,
    WEAVIATE,
    CHROMA_DB,
    ANDROID,
    ANDROID_STUDIO,
    FLUTTER,
    REACT_NATIVE,
    SWIFT_IOS,



    MICROSERVICES,
    SYSTEM_DESIGN,
    EVENT_DRIVEN_ARCHITECTURE,
    API_GATEWAY,
    SERVICE_DISCOVERY,


    JWT,
    OAUTH2,
    OPENID_CONNECT,

    // ===============================
    // BUILD TOOLS
    // ===============================

    MAVEN,
    GRADLE,
    NPM,
    YARN,

    // ===============================
    // TOOLS
    // ===============================

    JIRA,
    CONFLUENCE,

    // ===============================
    // OPERATING SYSTEM / SCRIPTING
    // ===============================

    LINUX,
    BASH,
    POWERSHELL,

    // ===============================
    // BUSINESS / ANALYTICS
    // ===============================

    POWER_BI,
    TABLEAU
}